/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.PromocionController;
import controlador.pedidoController;
import modelo.Producto;
import modelo.Pedidos;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Flores
 */
public class FormInterListPedidos extends javax.swing.JInternalFrame {
private pedidoController dao;
 private JTable table;
    private DefaultTableModel model;
    /**
     * Creates new form FormInterListPedidos
     */
    public FormInterListPedidos() {
        initComponents();
        this.setSize(new Dimension(780, 600));
        this.setTitle("Gestion de Pedidos");
        dao = new pedidoController();
        loadProductosConPromocion();
    }
    private void loadProductosConPromocion() {
        // Obtener el modelo de la tabla con los resultados del procedimiento almacenado
        DefaultTableModel tablaPromociones = dao.obtenerPedidos();

        if (tablaPromociones != null) {
            // Limpiar la tabla existente antes de asignar el nuevo modelo
            limpiarJtablePromociones();

            // Asignar el modelo a la tabla existente
            jtablePedidos.setModel(tablaPromociones);

            // Imprimir el contenido de la tabla para depuración (opcional)
            for (int i = 0; i < tablaPromociones.getRowCount(); i++) {
                for (int j = 0; j < tablaPromociones.getColumnCount(); j++) {
                    System.out.print(tablaPromociones.getValueAt(i, j) + " ");
                }
                System.out.println();
            }
        }
    }
        private void limpiarJtablePromociones() {

        DefaultTableModel listapedidos = (DefaultTableModel) jtablePedidos.getModel();
        listapedidos.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablePedidos = new javax.swing.JTable();
        btneliminardetallepedidos = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Detalle Pedidos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jtablePedidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre del Cliente", "Prpoducto", "Cantidad", "Precio", "Importe"
            }
        ));
        jScrollPane1.setViewportView(jtablePedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 750, 450));

        btneliminardetallepedidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btneliminardetallepedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarx32.png"))); // NOI18N
        btneliminardetallepedidos.setText("Eliminar");
        btneliminardetallepedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminardetallepedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminardetallepedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 230, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminardetallepedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminardetallepedidosActionPerformed
        int fila = jtablePedidos.getSelectedRow();
        int id_promocion;
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Detalle de pedido no seleccionado");
        } else {
            id_promocion = (int) jtablePedidos.getValueAt(fila, 0);
            Pedidos objEliminarPedidos = new Pedidos();
            if (id_promocion != 0) {
                objEliminarPedidos.setId_pedido(id_promocion);
                if (!dao.eliminarPedidos(objEliminarPedidos)) {
                    JOptionPane.showMessageDialog(this, "Error al Eliminar Pedido.");

                } else {
                    JOptionPane.showMessageDialog(this, "Pedido Eliminado con éxito...");
                    limpiarJtablePromociones();
                    loadProductosConPromocion();
                }
            }
        }
    }//GEN-LAST:event_btneliminardetallepedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneliminardetallepedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablePedidos;
    // End of variables declaration//GEN-END:variables
}
