/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.ProductController;
import controlador.BebidaController;
import controlador.ComidaController;
import modelo.Bebida;
import modelo.Comida;
import modelo.ModelProductos;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Flores
 */
public class FormInterProduct extends javax.swing.JInternalFrame {

    private ProductController productoController;
    private BebidaController bebidaController;
    private ComidaController comidaController;
    DefaultTableModel modeloProductos = new DefaultTableModel();
    DefaultTableModel modeloComida = new DefaultTableModel();
    DefaultTableModel modeloBebidas = new DefaultTableModel();

    /**
     * Creates new form FormInterProduct
     */
    public FormInterProduct() {
        productoController = new ProductController();
        bebidaController = new BebidaController();
        comidaController = new ComidaController();
        initComponents();
        this.setSize(new Dimension(900, 735));
        this.setTitle("Nuevos Productos");
        // Panel para mostrar tablas
        actualizarTablaProducto();
        actualizarTablaBebida();
        actualizarTablaComida();
        lbledittipoproducto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelDatos1 = new javax.swing.JPanel();
        txtTipo = new javax.swing.JComboBox<>();
        lbledittipoproducto = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanelBebidas = new javax.swing.JPanel();
        txtAlcoholica = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioBebida = new javax.swing.JTextField();
        txtVolumen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelDatos4 = new javax.swing.JPanel();
        txt_stock_producto3 = new javax.swing.JTextField();
        txtIngredientes = new javax.swing.JTextField();
        txtAlergenos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCalorias = new javax.swing.JTextField();
        txtPrecioComida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_stock_producto4 = new javax.swing.JTextField();
        txt_stock_producto5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBebida = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableComida = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAddBebida = new javax.swing.JButton();
        btnUpdateBebida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAddComida = new javax.swing.JButton();
        btnUpdateComida = new javax.swing.JButton();
        btnDeleteBebidas = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnDeleteComidas = new javax.swing.JButton();
        btnDeleteProductos = new javax.swing.JButton();
        btn_nurvos_productos = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Listado Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));
        jPanelDatos1.setToolTipText("");
        jPanelDatos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Bebida", "Comida" }));
        jPanelDatos1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 170, -1));
        jPanelDatos1.add(lbledittipoproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 140, 10));

        txtStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tipo Producto:");
        jPanelDatos1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Stok Producto:");
        jPanelDatos1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        txtIdProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos1.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nombre Producto:");
        jPanelDatos1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Producto:");
        jPanelDatos1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanelDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 80));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 730, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("GESTOR PRODUCTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jPanelBebidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Bedida"));
        jPanelBebidas.setToolTipText("");
        jPanelBebidas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelBebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAlcoholica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelBebidas.add(txtAlcoholica, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cont. Alcohol(true/false):");
        jPanelBebidas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        txtPrecioBebida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelBebidas.add(txtPrecioBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, -1));

        txtVolumen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelBebidas.add(txtVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Volumen:");
        jPanelBebidas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Precio:");
        jPanelBebidas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanelBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 740, 90));

        jPanelDatos4.setBorder(javax.swing.BorderFactory.createTitledBorder("Comida"));
        jPanelDatos4.setToolTipText("");
        jPanelDatos4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelDatos4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_stock_producto3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos4.add(txt_stock_producto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 170, -1));

        txtIngredientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos4.add(txtIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 170, -1));

        txtAlergenos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos4.add(txtAlergenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Ingredientes:");
        jPanelDatos4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Alergias:");
        jPanelDatos4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        txtCalorias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos4.add(txtCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        txtPrecioComida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos4.add(txtPrecioComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Precio:");
        jPanelDatos4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Calorias:");
        jPanelDatos4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        getContentPane().add(jPanelDatos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 740, 90));

        txt_stock_producto4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_stock_producto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 170, -1));

        txt_stock_producto5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_stock_producto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 170, -1));

        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Productos", "stock", "Tipo de Producto"
            }
        ));
        tableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 730, 110));

        tableBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Productos", "Stock", "Tipo", "Precio", "Volumen", "Alcoholica"
            }
        ));
        tableBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBebidaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBebida);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 730, 100));

        tableComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Productos", "Stock", "Tipo", "Precio", "Calorias", "Ingredientes", "Alergenos"
            }
        ));
        tableComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableComidaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableComida);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 730, 110));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btnAddBebida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario.png"))); // NOI18N
        btnAddBebida.setText("Agregar");
        btnAddBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBebidaActionPerformed(evt);
            }
        });

        btnUpdateBebida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnUpdateBebida.setText("Modificar");
        btnUpdateBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddBebida)
                    .addComponent(btnUpdateBebida))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAddBebida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateBebida)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 140, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btnAddComida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario.png"))); // NOI18N
        btnAddComida.setText("Agregar");
        btnAddComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddComidaActionPerformed(evt);
            }
        });

        btnUpdateComida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnUpdateComida.setText("Modificar");
        btnUpdateComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateComidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddComida)
                    .addComponent(btnUpdateComida))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnAddComida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateComida)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 140, 110));

        btnDeleteBebidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quitar-usuario.png"))); // NOI18N
        btnDeleteBebidas.setText("Eliminar");
        btnDeleteBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Listado Bebidas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 730, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Listado Comidas");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 730, 10));

        btnDeleteComidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteComidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quitar-usuario.png"))); // NOI18N
        btnDeleteComidas.setText("Eliminar");
        btnDeleteComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteComidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, -1, -1));

        btnDeleteProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quitar-usuario.png"))); // NOI18N
        btnDeleteProductos.setText("Eliminar");
        btnDeleteProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        btn_nurvos_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nurvos_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_nurvos_productos.setText("Nuevo");
        btn_nurvos_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nurvos_productosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nurvos_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBebidasActionPerformed
        // TODO add your handling code here:
        int fila = tableBebida.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Producto no seleccionado");
        } else {
            bebidaController.deleteBebida((String) tableBebida.getValueAt(fila, 0));

            JOptionPane.showMessageDialog(this, "Producto bebida Eliminado...");
            actualizarTablaProducto();
            actualizarTablaBebida();
        }
    }//GEN-LAST:event_btnDeleteBebidasActionPerformed

    private void btnAddBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBebidaActionPerformed
        // TODO add your handling code here:
        agregarBebida();
    }//GEN-LAST:event_btnAddBebidaActionPerformed

    private void btnUpdateBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBebidaActionPerformed
        // TODO add your handling code here:
        actualizarBebida();
    }//GEN-LAST:event_btnUpdateBebidaActionPerformed

    private void btnAddComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddComidaActionPerformed
        // TODO add your handling code here:
        agregarComida();
    }//GEN-LAST:event_btnAddComidaActionPerformed

    private void btnUpdateComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateComidaActionPerformed
        // TODO add your handling code here:
        actualizarComida();
    }//GEN-LAST:event_btnUpdateComidaActionPerformed

    private void btnDeleteComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteComidasActionPerformed
        // TODO add your handling code here:
        int fila = tableComida.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Producto no seleccionado");
        } else {
            comidaController.deleteComida((String) tableComida.getValueAt(fila, 0));
            JOptionPane.showMessageDialog(this, "Producto Comida Eliminado...");
            actualizarTablaProducto();
            actualizarTablaComida();
        }
    }//GEN-LAST:event_btnDeleteComidasActionPerformed

    private void btnDeleteProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductosActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        int fila = tableProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Producto no seleccionado");
        } else {
            productoController.deleteProducto((String) tableProducto.getValueAt(fila, 0));
            JOptionPane.showMessageDialog(this, "Producto Eliminado...");
            actualizarTablaProducto();
        }
    }//GEN-LAST:event_btnDeleteProductosActionPerformed

    private void tableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductoMouseClicked
        int fila = tableProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Producto no seleccionado");
        } else {
            txtIdProducto.setText((String) tableProducto.getValueAt(fila, 0).toString());
            txtNombre.setText((String) tableProducto.getValueAt(fila, 1).toString());
            txtStock.setText((String) tableProducto.getValueAt(fila, 2).toString());
            lbledittipoproducto.setText((String) tableProducto.getValueAt(fila, 3).toString());
            //txtTipo.getSelectedItem((String) tableProducto.getValueAt(fila, 0).toString()).toString();

        }
    }//GEN-LAST:event_tableProductoMouseClicked

    private void btn_nurvos_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nurvos_productosActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btn_nurvos_productosActionPerformed

    private void tableBebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBebidaMouseClicked
        limpiarCampos();
        int fila = tableBebida.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Producto no seleccionado");
        } else {
            txtIdProducto.setText((String) tableBebida.getValueAt(fila, 0).toString());
            txtNombre.setText((String) tableBebida.getValueAt(fila, 1).toString());
            txtStock.setText((String) tableBebida.getValueAt(fila, 2).toString());
            lbledittipoproducto.setText((String) tableBebida.getValueAt(fila, 3).toString());
            txtPrecioBebida.setText((String) tableBebida.getValueAt(fila, 4).toString());
            txtVolumen.setText((String) tableBebida.getValueAt(fila, 5).toString());
            txtAlcoholica.setText((String) tableBebida.getValueAt(fila, 6).toString());

        }
    }//GEN-LAST:event_tableBebidaMouseClicked

    private void tableComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableComidaMouseClicked
        limpiarCampos();
        int fila = tableComida.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Producto no seleccionado");
        } else {
            txtIdProducto.setText((String) tableComida.getValueAt(fila, 0).toString());
            txtNombre.setText((String) tableComida.getValueAt(fila, 1).toString());
            txtStock.setText((String) tableComida.getValueAt(fila, 2).toString());
            lbledittipoproducto.setText((String) tableComida.getValueAt(fila, 3).toString());

            txtPrecioComida.setText((String) tableComida.getValueAt(fila, 4).toString());
            txtCalorias.setText((String) tableComida.getValueAt(fila, 5).toString());
            txtIngredientes.setText((String) tableComida.getValueAt(fila, 6).toString());
            txtAlergenos.setText((String) tableComida.getValueAt(fila, 7).toString());

        }
    }//GEN-LAST:event_tableComidaMouseClicked

    private void agregarProducto() {
        String id = txtIdProducto.getText();
        String nombre = txtNombre.getText();
        int stock = Integer.parseInt(txtStock.getText());
        String tipo = txtTipo.getSelectedItem().toString();

        ModelProductos producto = new ModelProductos(id, nombre, stock, tipo);
        productoController.createProducto(producto);
        JOptionPane.showMessageDialog(this, "Producto agregado con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void actualizarProducto() {
        String id = txtIdProducto.getText();
        String nombre = txtNombre.getText();
        int stock = Integer.parseInt(txtStock.getText());
        String tipo = lbledittipoproducto.getText();

        ModelProductos producto = new ModelProductos(id, nombre, stock, tipo);
        productoController.updateProducto(producto);
        JOptionPane.showMessageDialog(this, "Producto actualizado con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void eliminarProducto() {
        String id = txtIdProducto.getText();
        productoController.deleteProducto(id);
        JOptionPane.showMessageDialog(this, "Producto eliminado con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void agregarBebida() {
        String id = txtIdProducto.getText();
        String nombre = txtNombre.getText();
        int stock = Integer.parseInt(txtStock.getText());
        String tipo = txtTipo.getSelectedItem().toString();
        double precio = Double.parseDouble(txtPrecioBebida.getText());
        double volumen = Double.parseDouble(txtVolumen.getText());
        boolean alcoholica = Boolean.parseBoolean(txtAlcoholica.getText());

        Bebida bebida = new Bebida(id, nombre, stock, tipo, precio, volumen, alcoholica);
        bebidaController.createBebida(bebida);
        JOptionPane.showMessageDialog(this, "Bebida agregada con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void actualizarBebida() {
        String id = txtIdProducto.getText();
        String nombre = txtNombre.getText();
        int stock = Integer.parseInt(txtStock.getText());
        String tipo = txtTipo.getSelectedItem().toString();
        double precio = Double.parseDouble(txtPrecioBebida.getText());
        double volumen = Double.parseDouble(txtVolumen.getText());
        boolean alcoholica = Boolean.parseBoolean(txtAlcoholica.getText());

        Bebida bebida = new Bebida(id, nombre, stock, tipo, precio, volumen, alcoholica);
        bebidaController.updateBebida(bebida);
        JOptionPane.showMessageDialog(this, "Bebida actualizada con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void eliminarBebida() {
        String id = txtIdProducto.getText();
        bebidaController.deleteBebida(id);
        JOptionPane.showMessageDialog(this, "Bebida eliminada con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void agregarComida() {
        String id = txtIdProducto.getText();
        String nombre = txtNombre.getText();
        int stock = Integer.parseInt(txtStock.getText());
        String tipo = txtTipo.getSelectedItem().toString();
        double precio = Double.parseDouble(txtPrecioComida.getText());
        int calorias = Integer.parseInt(txtCalorias.getText());
        String ingredientes = txtIngredientes.getText();
        String alergenos = txtAlergenos.getText();

        Comida comida = new Comida(id, nombre, stock, tipo, precio, calorias, ingredientes, alergenos);
        comidaController.createComida(comida);
        JOptionPane.showMessageDialog(this, "Comida agregada con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void actualizarComida() {
        String id = txtIdProducto.getText();
        String nombre = txtNombre.getText();
        int stock = Integer.parseInt(txtStock.getText());
        String tipo = txtTipo.getSelectedItem().toString();
        double precio = Double.parseDouble(txtPrecioComida.getText());
        int calorias = Integer.parseInt(txtCalorias.getText());
        String ingredientes = txtIngredientes.getText();
        String alergenos = txtAlergenos.getText();

        Comida comida = new Comida(id, nombre, stock, tipo, precio, calorias, ingredientes, alergenos);
        comidaController.updateComida(comida);
        JOptionPane.showMessageDialog(this, "Comida actualizada con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void eliminarComida() {
        String id = txtIdProducto.getText();
        comidaController.deleteComida(id);
        JOptionPane.showMessageDialog(this, "Comida eliminada con éxito.");
        actualizarTablas();
        limpiarCampos();
    }

    private void actualizarTablas() {
        actualizarTablaProducto();
        actualizarTablaBebida();
        actualizarTablaComida();
    }

    private void actualizarTablaProducto() {
        DefaultTableModel model = (DefaultTableModel) tableProducto.getModel();
        model.setRowCount(0); // Limpiar tabla
        for (ModelProductos p : productoController.getAllProductos()) {
            model.addRow(new Object[]{p.getIdProducto(), p.getNombre(), p.getStock(), p.getTipo()});
        }
    }

    private void actualizarTablaBebida() {
        DefaultTableModel model = (DefaultTableModel) tableBebida.getModel();
        model.setRowCount(0); // Limpiar tabla
        for (Bebida b : bebidaController.getAllBebidas()) {
            model.addRow(new Object[]{b.getId_producto(), b.getNombre(), b.getStock(), b.getTipo(), b.getPrecio(), b.getVolumen(), b.isAlcoholica()});
        }
    }

    private void actualizarTablaComida() {
        DefaultTableModel model = (DefaultTableModel) tableComida.getModel();
        model.setRowCount(0); // Limpiar tabla
        for (Comida c : comidaController.getAllComidas()) {
            model.addRow(new Object[]{c.getId_producto(), c.getNombre(), c.getStock(), c.getTipo(), c.getPrecio(), c.getCalorias(), c.getIngredientes(), c.getAlergenos()});
        }
    }

    private void limpiarCampos() {
        txtIdProducto.setText("");
        txtNombre.setText("");
        txtStock.setText("");
        txtTipo.setSelectedItem(0);
        txtPrecioBebida.setText("");
        txtVolumen.setText("");
        txtAlcoholica.setText("");
        txtPrecioComida.setText("");
        txtCalorias.setText("");
        txtIngredientes.setText("");
        txtAlergenos.setText("");
        lbledittipoproducto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBebida;
    private javax.swing.JButton btnAddComida;
    private javax.swing.JButton btnDeleteBebidas;
    private javax.swing.JButton btnDeleteComidas;
    private javax.swing.JButton btnDeleteProductos;
    private javax.swing.JButton btnUpdateBebida;
    private javax.swing.JButton btnUpdateComida;
    private javax.swing.JButton btn_nurvos_productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBebidas;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JPanel jPanelDatos4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbledittipoproducto;
    private javax.swing.JTable tableBebida;
    private javax.swing.JTable tableComida;
    private javax.swing.JTable tableProducto;
    private javax.swing.JTextField txtAlcoholica;
    private javax.swing.JTextField txtAlergenos;
    private javax.swing.JTextField txtCalorias;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIngredientes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioBebida;
    private javax.swing.JTextField txtPrecioComida;
    private javax.swing.JTextField txtStock;
    private javax.swing.JComboBox<String> txtTipo;
    private javax.swing.JTextField txtVolumen;
    private javax.swing.JTextField txt_stock_producto3;
    private javax.swing.JTextField txt_stock_producto4;
    private javax.swing.JTextField txt_stock_producto5;
    // End of variables declaration//GEN-END:variables
}
