package vista;
import controlador.empleadoController;
import modelo.Empleado;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Flores
 */
public class FormInterEmpleado extends javax.swing.JInternalFrame {
    private empleadoController ctr_empleado;
    public FormInterEmpleado() {
        ctr_empleado = new empleadoController();
        initComponents();
        this.setSize(new Dimension(770, 665));
        this.setTitle("Nuevo Empleado");
        // Configuración de la tabla

        listarEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo_empleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellido_empleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_dni_empleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_direccion_empleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_pais_empleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_puesto_empleado = new javax.swing.JTextField();
        txt_nombre_empleado1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanelDatos1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_usuario_empleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_clave_empleado = new javax.swing.JTextField();
        jPanelDatos2 = new javax.swing.JPanel();
        btn_guardar_empleados = new javax.swing.JButton();
        btn_editar_empleados = new javax.swing.JButton();
        btn_eliminar_empleados = new javax.swing.JButton();
        btn_buscar_empleados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("GESTOR DE EMPLEADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Empleado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txt_codigo_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_codigo_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos Empleado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txt_apellido_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_apellido_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DNI Empleado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txt_dni_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_dni_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Direccion Empleado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txt_direccion_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_direccion_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Pais Empleado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        txt_pais_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_pais_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Puesto Empleado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        txt_puesto_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_puesto_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 170, -1));

        txt_nombre_empleado1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre_empleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nombre Empleado:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanelDatos1.setToolTipText("");
        jPanelDatos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Usuario Empleado");
        jPanelDatos1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        txt_usuario_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_usuario_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuario_empleadoActionPerformed(evt);
            }
        });
        jPanelDatos1.add(txt_usuario_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Contraseña Empleado:");
        jPanelDatos1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        txt_clave_empleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanelDatos1.add(txt_clave_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 170, -1));

        getContentPane().add(jPanelDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 740, 200));

        jPanelDatos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanelDatos2.setToolTipText("");
        jPanelDatos2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btn_guardar_empleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario.png"))); // NOI18N
        btn_guardar_empleados.setText("Agregar");
        btn_guardar_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_empleadosActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_guardar_empleados);

        btn_editar_empleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editar_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btn_editar_empleados.setText("Modificar");
        btn_editar_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_empleadosActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_editar_empleados);

        btn_eliminar_empleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quitar-usuario.png"))); // NOI18N
        btn_eliminar_empleados.setText("Eliminar");
        btn_eliminar_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_empleadosActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_eliminar_empleados);

        btn_buscar_empleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_buscar_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_buscar_empleados.setText("Nuevo");
        btn_buscar_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_empleadosActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_buscar_empleados);

        getContentPane().add(jPanelDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 740, 80));

        jTableEmpleados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombres", "Apellidos", "Dni", "Direccion", "Pais", "Puesto", "Usuario", "Clave"
            }
        ));
        jTableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableEmpleados.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTableEmpleados.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTableEmpleados.getColumnModel().getColumn(4).setPreferredWidth(85);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 730, 230));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Listado Empleados");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 730, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardar_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_empleadosActionPerformed

        Empleado objEmpleado = new Empleado();
        if (!txt_codigo_empleado.getText().isEmpty()) {
            objEmpleado.setId_empleado(txt_codigo_empleado.getText().trim());
            objEmpleado.setNombre(txt_nombre_empleado1.getText().trim()); // Nombre del empleado
            objEmpleado.setApellido(txt_apellido_empleado.getText().trim()); // Apellido del empleado
            objEmpleado.setDni(Integer.parseInt(txt_dni_empleado.getText().trim())); // DNI del empleado
            objEmpleado.setDireccion(txt_direccion_empleado.getText().trim());
            objEmpleado.setPais(txt_pais_empleado.getText().trim());
            objEmpleado.setPuesto(txt_puesto_empleado.getText().trim());
            objEmpleado.setUsuario(txt_usuario_empleado.getText().trim());
            objEmpleado.setClave(txt_clave_empleado.getText().trim());

            if (ctr_empleado.registrarEmpleado(objEmpleado)) {
                JOptionPane.showMessageDialog(this, "Empleado registrado exitosamente");
                limpíarFields();
                limpiarJtableEmpleados();
                listarEmpleados();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar al empleado.");
                limpíarFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
                limpíarFields();
        }

    }//GEN-LAST:event_btn_guardar_empleadosActionPerformed

    private void btn_editar_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_empleadosActionPerformed
        Empleado objEmpleadoEditar = new Empleado();
        if (!txt_codigo_empleado.getText().isEmpty()) {
            objEmpleadoEditar.setId_empleado(txt_codigo_empleado.getText().trim());
            objEmpleadoEditar.setNombre(txt_nombre_empleado1.getText().trim()); // Nombre del empleado
            objEmpleadoEditar.setApellido(txt_apellido_empleado.getText().trim()); // Apellido del empleado
            objEmpleadoEditar.setDni(Integer.parseInt(txt_dni_empleado.getText().trim())); // DNI del empleado
            objEmpleadoEditar.setDireccion(txt_direccion_empleado.getText().trim());
            objEmpleadoEditar.setPais(txt_pais_empleado.getText().trim());
            objEmpleadoEditar.setPuesto(txt_puesto_empleado.getText().trim());
            objEmpleadoEditar.setUsuario(txt_usuario_empleado.getText().trim());
            objEmpleadoEditar.setClave(txt_clave_empleado.getText().trim());
            if(!ctr_empleado.modificarEmpleado(objEmpleadoEditar)) {
                JOptionPane.showMessageDialog(this, "Error al Actualizar empleado.");
                limpíarFields();
            } else {
                JOptionPane.showMessageDialog(this, "Empleado actualizado...");
                limpíarFields();
                limpiarJtableEmpleados();
                listarEmpleados();
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
                limpíarFields();
        }
    }//GEN-LAST:event_btn_editar_empleadosActionPerformed

    private void btn_eliminar_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_empleadosActionPerformed
        int fila = jTableEmpleados.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(null, "Empleado no seleccionado");
        } else {
            txt_codigo_empleado.setText((String)jTableEmpleados.getValueAt(fila, 0));
            Empleado objEmpleadoEliminar = new Empleado();
              if (!txt_codigo_empleado.getText().isEmpty()) {
                objEmpleadoEliminar.setId_empleado(txt_codigo_empleado.getText().trim());
                if(!ctr_empleado.EliminarEmpleado(objEmpleadoEliminar)) {
                    JOptionPane.showMessageDialog(this, "Error al Eliminar empleado.");
                    limpíarFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Empleado Eliminado...");
                    limpíarFields();
                    limpiarJtableEmpleados();
                    listarEmpleados();
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
                    limpíarFields();
            }
        }
    }//GEN-LAST:event_btn_eliminar_empleadosActionPerformed

    private void btn_buscar_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_empleadosActionPerformed
        limpíarFields();
    }//GEN-LAST:event_btn_buscar_empleadosActionPerformed

    private void txt_usuario_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuario_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuario_empleadoActionPerformed

    private void jTableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleadosMouseClicked
        int fila = jTableEmpleados.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(null, "Empleado no seleccionado");
        } else {
            txt_codigo_empleado.setText((String)jTableEmpleados.getValueAt(fila, 0));
            txt_nombre_empleado1.setText((String)jTableEmpleados.getValueAt(fila, 1));
            txt_apellido_empleado.setText((String)jTableEmpleados.getValueAt(fila, 2));
            txt_dni_empleado.setText(""+Integer.parseInt((String)jTableEmpleados.getValueAt(fila, 3).toString()));
            txt_direccion_empleado.setText((String)jTableEmpleados.getValueAt(fila, 4));
            txt_pais_empleado.setText((String)jTableEmpleados.getValueAt(fila, 5));
            txt_puesto_empleado.setText((String)jTableEmpleados.getValueAt(fila, 6));
            txt_usuario_empleado.setText((String)jTableEmpleados.getValueAt(fila, 7));
            txt_clave_empleado.setText((String)jTableEmpleados.getValueAt(fila, 8));
            
        }
    }//GEN-LAST:event_jTableEmpleadosMouseClicked
    private void listarEmpleados() {
        List<Empleado> empleados = ctr_empleado.listarEmpleados();
        DefaultTableModel tablaEmpleados = (DefaultTableModel) jTableEmpleados.getModel();
        for (Empleado emp : empleados) {
            tablaEmpleados.addRow(new Object[]{
                emp.getId_empleado(),
                emp.getNombre(),
                emp.getApellido(),
                emp.getDni(),
                emp.getDireccion(),
                emp.getPais(),
                emp.getPuesto(),
                emp.getUsuario(),
                emp.getClave()
            });
        }
    }
    private void limpiarJtableEmpleados(){
        DefaultTableModel tablaEmpleados = (DefaultTableModel) jTableEmpleados.getModel();
        tablaEmpleados.setRowCount(0);
    }
    private void limpíarFields() {
        txt_codigo_empleado.setText("");
        txt_nombre_empleado1.setText("");
        txt_apellido_empleado.setText("");
        txt_dni_empleado.setText("");
        txt_direccion_empleado.setText("");
        txt_pais_empleado.setText("");
        txt_puesto_empleado.setText("");
        txt_usuario_empleado.setText("");
        txt_clave_empleado.setText("");
        txt_codigo_empleado.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_empleados;
    private javax.swing.JButton btn_editar_empleados;
    private javax.swing.JButton btn_eliminar_empleados;
    private javax.swing.JButton btn_guardar_empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JPanel jPanelDatos2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField txt_apellido_empleado;
    private javax.swing.JTextField txt_clave_empleado;
    private javax.swing.JTextField txt_codigo_empleado;
    private javax.swing.JTextField txt_direccion_empleado;
    private javax.swing.JTextField txt_dni_empleado;
    private javax.swing.JTextField txt_nombre_empleado1;
    private javax.swing.JTextField txt_pais_empleado;
    private javax.swing.JTextField txt_puesto_empleado;
    private javax.swing.JTextField txt_usuario_empleado;
    // End of variables declaration//GEN-END:variables
}
