package vista;

import controlador.clienteController;
import controlador.productoController;
import modelo.Cliente;
import modelo.Producto;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Flores
 */
public class FormInterProducto extends javax.swing.JInternalFrame {

    private productoController controladorProducto;

    /**
     * Creates new form FormInterProducto
     */
    public FormInterProducto() {
        controladorProducto = new productoController();
        initComponents();
        this.setSize(new Dimension(769, 622));
        this.setTitle("Nuevos Productos");
        listarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo_producto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_stock_producto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre_product = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanelDatos1 = new javax.swing.JPanel();
        jComboBoxProduct = new javax.swing.JComboBox<>();
        jPanelDatos2 = new javax.swing.JPanel();
        btn_guardar_producto = new javax.swing.JButton();
        btn_editar_producto = new javax.swing.JButton();
        btn_eliminar_producto = new javax.swing.JButton();
        btn_nuevos_producto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Listado Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_codigo_producto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_codigo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Stok Producto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        txt_stock_producto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_stock_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tipo Producto:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        txt_nombre_product.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nombre Producto:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanelDatos1.setToolTipText("");
        jPanelDatos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Comida" }));
        jPanelDatos1.add(jComboBoxProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 170, -1));

        getContentPane().add(jPanelDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 740, 110));

        jPanelDatos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanelDatos2.setToolTipText("");
        jPanelDatos2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btn_guardar_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario.png"))); // NOI18N
        btn_guardar_producto.setText("Agregar");
        btn_guardar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_productoActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_guardar_producto);

        btn_editar_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btn_editar_producto.setText("Modificar");
        btn_editar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_productoActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_editar_producto);

        btn_eliminar_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quitar-usuario.png"))); // NOI18N
        btn_eliminar_producto.setText("Eliminar");
        btn_eliminar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_productoActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_eliminar_producto);

        btn_nuevos_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nuevos_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_nuevos_producto.setText("Nuevo");
        btn_nuevos_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevos_productoActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_nuevos_producto);

        getContentPane().add(jPanelDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 740, 90));

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombres", "Stock", "tipo"
            }
        ));
        jTableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 730, 240));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 730, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("GESTOR PRODUCTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoMouseClicked
        int fila = jTableProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Cliente no seleccionado");
        } else {
            txt_codigo_producto.setText((String) jTableProducto.getValueAt(fila, 0));
            txt_nombre_product.setText((String) jTableProducto.getValueAt(fila, 1));
            txt_stock_producto.setText("" + Integer.parseInt((String) jTableProducto.getValueAt(fila, 2).toString()));
            jComboBoxProduct.setSelectedItem((String) jTableProducto.getValueAt(fila, 3));
 
        }
    }//GEN-LAST:event_jTableProductoMouseClicked

    private void btn_guardar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_productoActionPerformed

        if (!txt_codigo_producto.getText().isEmpty() && !txt_nombre_product.getText().isEmpty() && !txt_stock_producto.getText().isEmpty()) {
            String idProducto = (txt_codigo_producto.getText().trim());
            String nombreProducto = txt_nombre_product.getText().trim();
            int stockProducto = Integer.parseInt(txt_stock_producto.getText().trim());
            String tipoProducto = (String) jComboBoxProduct.getSelectedItem();

            Producto objProducto = new Producto(idProducto, nombreProducto, stockProducto, tipoProducto) {

                @Override
                public double getPrecio() {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void aplicarDescuento(double porcentajeDescuento) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void aplicarPromocion(double porcentajeDescuento) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            };
            if (controladorProducto.registrarProducto(objProducto)) {
                JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente");
                limpíarFieldsProduct();
                limpiarJtableProducto();
                listarProductos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar al Cliente.");
                limpíarFieldsProduct();
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
            limpíarFieldsProduct();
        }


    }//GEN-LAST:event_btn_guardar_productoActionPerformed

    private void btn_editar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_productoActionPerformed
        if (!txt_codigo_producto.getText().isEmpty() && !txt_nombre_product.getText().isEmpty() && !txt_stock_producto.getText().isEmpty()) {
            String idProducto = (txt_codigo_producto.getText().trim());
            String nombreProducto = txt_nombre_product.getText().trim();
            int stockProducto = Integer.parseInt(txt_stock_producto.getText().trim());
            String tipoProducto = (String) jComboBoxProduct.getSelectedItem();

            Producto objProducto = new Producto(idProducto, nombreProducto, stockProducto, tipoProducto) {

                @Override
                public double getPrecio() {
                    throw new UnsupportedOperationException("Not supported yet.");
                }

                @Override
                public void aplicarDescuento(double porcentajeDescuento) {
                    throw new UnsupportedOperationException("Not supported yet.");
                }

                @Override
                public void aplicarPromocion(double porcentajeDescuento) {
                    throw new UnsupportedOperationException("Not supported yet.");
                }
            };
            if (controladorProducto.modificarProducto(objProducto)) {
                JOptionPane.showMessageDialog(this, "Producto Actualizado exitosamente");
                limpíarFieldsProduct();
                limpiarJtableProducto();
                listarProductos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar al Producto.");
                limpíarFieldsProduct();
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
            limpíarFieldsProduct();
        }
    }//GEN-LAST:event_btn_editar_productoActionPerformed

    private void btn_eliminar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_productoActionPerformed
        int fila = jTableProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Producto no seleccionado");
        } else {
            if (!txt_codigo_producto.getText().isEmpty()) {
                String idProducto = (String)txt_codigo_producto.getText().trim();
                Producto objProducto = new Producto(idProducto, null, 0, null) {
                    @Override
                    public double getPrecio() {
                        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    }
                    
                    @Override
                    public void aplicarDescuento(double porcentajeDescuento) {
                        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    }
                    
                    @Override
                    public void aplicarPromocion(double porcentajeDescuento) {
                        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                    }
                };
                if (!controladorProducto.EliminarProducto(objProducto)) {
                    JOptionPane.showMessageDialog(this, "Error al Eliminar Cliente.");
                    limpíarFieldsProduct();
                } else {
                    JOptionPane.showMessageDialog(this, "Cliente Eliminado...");
                    limpíarFieldsProduct();
                    limpiarJtableProducto();
                    listarProductos();
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
                limpíarFieldsProduct();
            }
        }
    }//GEN-LAST:event_btn_eliminar_productoActionPerformed

    private void btn_nuevos_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevos_productoActionPerformed
        limpíarFieldsProduct();
         jComboBoxProduct.setSelectedIndex(0);
    }//GEN-LAST:event_btn_nuevos_productoActionPerformed
    private void limpiarJtableProducto() {
        DefaultTableModel tablaCliente = (DefaultTableModel) jTableProducto.getModel();
        tablaCliente.setRowCount(0);
    }

    private void limpíarFieldsProduct() {
        txt_codigo_producto.setText("");
        txt_nombre_product.setText("");
        txt_stock_producto.setText("");
         jComboBoxProduct.setSelectedIndex(0);
        txt_codigo_producto.requestFocus();
    }

    private void listarProductos() {
        List<Producto> listProduct = productoController.listarProductos();
        DefaultTableModel tablaClientes = (DefaultTableModel) jTableProducto.getModel();
        for (Producto producto : listProduct) {
            tablaClientes.addRow(new Object[]{
                producto.getId_producto(),
                producto.getNombre(),
                producto.getStock(),
                producto.getTipo(),});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar_producto;
    private javax.swing.JButton btn_eliminar_producto;
    private javax.swing.JButton btn_guardar_producto;
    private javax.swing.JButton btn_nuevos_producto;
    private javax.swing.JComboBox<String> jComboBoxProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JPanel jPanelDatos2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTextField txt_codigo_producto;
    private javax.swing.JTextField txt_nombre_product;
    private javax.swing.JTextField txt_stock_producto;
    // End of variables declaration//GEN-END:variables
}
