package vista;

import conexion.Conexion;
import java.awt.Dimension;
import controlador.clienteController;
import modelo.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jorge Flores
 */
public class FormInterCliente extends javax.swing.JInternalFrame {

    private clienteController controladorClinte;

    /**
     * Creates new form FormInterCliente
     */
    public FormInterCliente() {
        controladorClinte = new clienteController();
        initComponents();
        this.setSize(new Dimension(775, 665));
        this.setTitle("Nuevo Cliente");
        listarClientes();
        llenarCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_apellido_cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_dni_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_celular_cliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre_cliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanelDatos1 = new javax.swing.JPanel();
        jComboBox_genero_cliente = new javax.swing.JComboBox<>();
        jComboBoxEmpleado = new javax.swing.JComboBox<>();
        jPanelDatos2 = new javax.swing.JPanel();
        btn_guardar_cliente = new javax.swing.JButton();
        btn_editar_cliente = new javax.swing.JButton();
        btn_eliminar_cliente = new javax.swing.JButton();
        btn_nuevos_clientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("GESTOR CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo Clinte");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_codigo_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_codigo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos del Cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txt_apellido_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_apellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DNI Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txt_dni_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_dni_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Genero Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Numero Celular:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        txt_celular_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_celular_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("codigo Empleado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        txt_nombre_cliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nombre Cliente:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanelDatos1.setToolTipText("");
        jPanelDatos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_genero_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_genero_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otros" }));
        jPanelDatos1.add(jComboBox_genero_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, -1));

        jComboBoxEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanelDatos1.add(jComboBoxEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 170, -1));

        getContentPane().add(jPanelDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 740, 200));

        jPanelDatos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanelDatos2.setToolTipText("");
        jPanelDatos2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btn_guardar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_guardar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario.png"))); // NOI18N
        btn_guardar_cliente.setText("Agregar");
        btn_guardar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_clienteActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_guardar_cliente);

        btn_editar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btn_editar_cliente.setText("Modificar");
        btn_editar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_clienteActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_editar_cliente);

        btn_eliminar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_eliminar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quitar-usuario.png"))); // NOI18N
        btn_eliminar_cliente.setText("Eliminar");
        btn_eliminar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_clienteActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_eliminar_cliente);

        btn_nuevos_clientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nuevos_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_nuevos_clientes.setText("Nuevo");
        btn_nuevos_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevos_clientesActionPerformed(evt);
            }
        });
        jPanelDatos2.add(btn_nuevos_clientes);

        getContentPane().add(jPanelDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 740, 90));

        jTableCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombres", "Apellidos", "Dni", "Genero", "numero Celular", "Empleado"
            }
        ));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 730, 220));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Listado Clientes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 730, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        int fila = jTableCliente.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(null, "Cliente no seleccionado");
        } else {
            txt_codigo_cliente.setText((String)jTableCliente.getValueAt(fila, 0));
            txt_nombre_cliente.setText((String)jTableCliente.getValueAt(fila, 1));
            txt_apellido_cliente.setText((String)jTableCliente.getValueAt(fila, 2));
            txt_dni_cliente.setText(""+Integer.parseInt((String)jTableCliente.getValueAt(fila, 3).toString()));
            //jComboBox_genero_cliente.addItem((String)jTableCliente.getValueAt(fila, 4));
            jComboBox_genero_cliente.enable(false);
            txt_celular_cliente.setText(""+Integer.parseInt((String)jTableCliente.getValueAt(fila, 5).toString()));
        }
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void btn_guardar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_clienteActionPerformed

        Cliente objCliente = new Cliente();
        String empleado = jComboBoxEmpleado.getSelectedItem().toString();
        if (!txt_codigo_cliente.getText().isEmpty()) {
            objCliente.setId_cliente(txt_codigo_cliente.getText().trim());
            objCliente.setNombre(txt_nombre_cliente.getText().trim());
            objCliente.setApellido(txt_apellido_cliente.getText().trim());
            objCliente.setDNI(Integer.parseInt(txt_dni_cliente.getText().trim()));
            objCliente.setGenero((String) jComboBox_genero_cliente.getSelectedItem());
            objCliente.setNumeroCelular(Integer.parseInt(txt_celular_cliente.getText().trim()));
            objCliente.setId_empleado((String) jComboBoxEmpleado.getSelectedItem());
            if (controladorClinte.RegistrarClientes(objCliente)) {
                JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente");
                limpíarFields();
                limpiarJtableCliente();
                listarClientes();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar al Cliente.");
                limpíarFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
            limpíarFields();
        }
    }//GEN-LAST:event_btn_guardar_clienteActionPerformed

    private void btn_editar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_clienteActionPerformed
        Cliente objEditarCliente = new Cliente();
        if (!txt_codigo_cliente.getText().isEmpty()) {
             objEditarCliente.setId_cliente(txt_codigo_cliente.getText().trim());
            objEditarCliente.setNombre(txt_nombre_cliente.getText().trim());
            objEditarCliente.setApellido(txt_apellido_cliente.getText().trim());
            objEditarCliente.setDNI(Integer.parseInt(txt_dni_cliente.getText().trim()));
          
            objEditarCliente.setNumeroCelular(Integer.parseInt(txt_celular_cliente.getText().trim()));
            objEditarCliente.setId_empleado((String) jComboBoxEmpleado.getSelectedItem());
            if(!controladorClinte.modificarCliente(objEditarCliente)) {
                JOptionPane.showMessageDialog(this, "Error al Actualizar Cliente.");
                limpíarFields();
            } else {
                JOptionPane.showMessageDialog(this, "Cliente actualizado...");
                limpíarFields();
                limpiarJtableCliente();
                listarClientes();
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
            limpíarFields();
        }
    }//GEN-LAST:event_btn_editar_clienteActionPerformed

    private void btn_eliminar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_clienteActionPerformed
        int fila = jTableCliente.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(null, "Cliente no seleccionado");
        } else {
            txt_codigo_cliente.setText((String)jTableCliente.getValueAt(fila, 0));
            Cliente objClienteEliminar = new Cliente();
            if (!txt_codigo_cliente.getText().isEmpty()) {
                objClienteEliminar.setId_cliente(txt_codigo_cliente.getText().trim());
                if(!controladorClinte.eliminarCliente(objClienteEliminar)) {
                    JOptionPane.showMessageDialog(this, "Error al Eliminar Cliente.");
                    limpíarFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Cliente Eliminado...");
                    limpíarFields();
                    limpiarJtableCliente();
                    listarClientes();
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo de texto está vacío.");
                limpíarFields();
            }
        }
    }//GEN-LAST:event_btn_eliminar_clienteActionPerformed

    private void btn_nuevos_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevos_clientesActionPerformed
        limpíarFields();
    }//GEN-LAST:event_btn_nuevos_clientesActionPerformed
    private void limpiarJtableCliente() {
        DefaultTableModel tablaCliente = (DefaultTableModel) jTableCliente.getModel();
        tablaCliente.setRowCount(0);
    }

    private void limpíarFields() {
        txt_codigo_cliente.setText("");
        txt_nombre_cliente.setText("");
        txt_apellido_cliente.setText("");
        txt_dni_cliente.setText("");
        txt_celular_cliente.setText("");
        jComboBox_genero_cliente.enable(true);
        txt_codigo_cliente.requestFocus();
    }

    private void listarClientes() {
        List<Cliente> listClientes = controladorClinte.ListarClientes();
        DefaultTableModel tablaClientes = (DefaultTableModel) jTableCliente.getModel();
        for (Cliente Clientes : listClientes) {
            tablaClientes.addRow(new Object[]{
                Clientes.getId_cliente(),
                Clientes.getNombre(),
                Clientes.getApellido(),
                Clientes.getDNI(),
                Clientes.getGenero(),
                Clientes.getNumeroCelular(),
                Clientes.getId_empleado()
            });
        }
    }

    private void llenarCombobox() {
        Conexion conect = new Conexion();
        DefaultComboBoxModel comboEmpleados = (DefaultComboBoxModel) jComboBoxEmpleado.getModel();
        String query = "{CALL sp_listaEmpleados}";
        Connection condb = conect.conectar();
        try (CallableStatement stmt = condb.prepareCall(query)) {
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String item = rs.getString("id_empleado");
                jComboBoxEmpleado.addItem(item);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar_cliente;
    private javax.swing.JButton btn_eliminar_cliente;
    private javax.swing.JButton btn_guardar_cliente;
    private javax.swing.JButton btn_nuevos_clientes;
    private javax.swing.JComboBox<String> jComboBoxEmpleado;
    private javax.swing.JComboBox<String> jComboBox_genero_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelDatos1;
    private javax.swing.JPanel jPanelDatos2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField txt_apellido_cliente;
    private javax.swing.JTextField txt_celular_cliente;
    private javax.swing.JTextField txt_codigo_cliente;
    private javax.swing.JTextField txt_dni_cliente;
    private javax.swing.JTextField txt_nombre_cliente;
    // End of variables declaration//GEN-END:variables
}
