/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.productoController;
import modelo.Bebida;
import modelo.Comida;
import modelo.Producto;
import static vista.FrmMenu.jDesktopPane_menu;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Flores
 */
public class FormInterMenus extends javax.swing.JInternalFrame {

    private static List<Producto> productos = new ArrayList<>();

    /**
     * Creates new form FormInterMenus
     */
    public FormInterMenus() {
        initComponents();
        this.setSize(new Dimension(1200, 620));
        this.setTitle("LISTADO MENUS");
        listarTablaComidas();
        listarTablaBedidas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductComida = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductBebidas = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIrComidas = new javax.swing.JButton();
        btnIrBebidas = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MENU DE PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jTableProductComida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableProductComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Producto", "Stock", "Tipo", "Precio", "Calorias", "Ingredientes", "Alergenos"
            }
        ));
        jScrollPane1.setViewportView(jTableProductComida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 600, 310));

        jTableProductBebidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableProductBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Producto", "Stock", "Tipo", "Precio", "Volumen", "Cant Alcohol"
            }
        ));
        jScrollPane2.setViewportView(jTableProductBebidas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 550, 310));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 580, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 550, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Listado Bebidas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Listado Comidas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btnIrComidas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIrComidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entrega-de-comida.png"))); // NOI18N
        btnIrComidas.setText("Realizar Pedido Comidas");
        btnIrComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrComidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnIrComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 290, 40));

        btnIrBebidas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnIrBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedido-cafe.png"))); // NOI18N
        btnIrBebidas.setText("Realizar Pedido Bebidas");
        btnIrBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnIrBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 280, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrComidasActionPerformed

        String tipoproducto = "Comida";
        FormInterPedidos formpedido = new FormInterPedidos();
        formpedido.TipoProduto(tipoproducto);
        jDesktopPane_menu.add(formpedido);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = formpedido.getSize();
        formpedido.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formpedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrComidasActionPerformed

    private void btnIrBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrBebidasActionPerformed

        String tipoproducto = "Bebida";
        FormInterPedidos formpedido = new FormInterPedidos();
        formpedido.TipoProduto(tipoproducto);
        jDesktopPane_menu.add(formpedido);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = formpedido.getSize();
        formpedido.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formpedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrBebidasActionPerformed
    private void listarTablaBedidas() {
        String tipoProducto = "Bebida";
        List<Bebida> bebidas = productoController.ListarPorductosBebida(tipoProducto);
        DefaultTableModel tablaProductbebidas = (DefaultTableModel) jTableProductBebidas.getModel();
        for (Bebida prodctBebida : bebidas) {
            tablaProductbebidas.addRow(new Object[]{
                prodctBebida.getId_producto(),
                prodctBebida.getNombre(),
                prodctBebida.getStock(),
                prodctBebida.getTipo(),
                prodctBebida.getPrecio(),
                prodctBebida.getVolumen(),
                prodctBebida.isAlcoholica()
            });
        }
    }

    private void listarTablaComidas() {
        String tipoProducto = "Comida";
        List<Comida> comidas = productoController.ListarPorductosComida(tipoProducto);
        DefaultTableModel tablaProductComida = (DefaultTableModel) jTableProductComida.getModel();
        for (Comida prodctComida : comidas) {
            tablaProductComida.addRow(new Object[]{
                prodctComida.getId_producto(),
                prodctComida.getNombre(),
                prodctComida.getStock(),
                prodctComida.getTipo(),
                prodctComida.getPrecio(),
                prodctComida.getCalorias(),
                prodctComida.getIngredientes(),
                prodctComida.getAlergenos()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrBebidas;
    private javax.swing.JButton btnIrComidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableProductBebidas;
    private javax.swing.JTable jTableProductComida;
    // End of variables declaration//GEN-END:variables
}
