package vista;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Jorge Flores
 */
public class FrmMenu extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema Cafeteria");
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));

        JPanel backgroundPanel = new JPanel();
        backgroundPanel.setBackground(new Color(247, 232, 210)); // Color beige
        backgroundPanel.setBounds(0, 0, ancho, (alto - 110));

        jDesktopPane_menu.add(backgroundPanel, JLayeredPane.DEFAULT_LAYER);

        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_gestor_empleados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_gestionar_clientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_actualizar_productos = new javax.swing.JMenuItem();
        jMenuItem_gestionar_productos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemMostrarPlatos = new javax.swing.JMenuItem();
        jMenuRealizarPedido = new javax.swing.JMenuItem();
        jMenuIPedidoComidas = new javax.swing.JMenuItem();
        jMenuPedidoBebidas = new javax.swing.JMenuItem();
        jMenuListaPedido = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 240, 230));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setBackground(new java.awt.Color(101, 67, 33));

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleados.png"))); // NOI18N
        jMenu1.setText("Empleados");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_gestor_empleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_gestor_empleados.setText("Gestionar Empleados");
        jMenuItem_gestor_empleados.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_gestor_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestor_empleadosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_gestor_empleados);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente_icon.png"))); // NOI18N
        jMenu2.setText("Clientes");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_gestionar_clientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_gestionar_clientes.setText("Gestionar Clientes");
        jMenuItem_gestionar_clientes.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_gestionar_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_clientesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_gestionar_clientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu3.setText("Productos");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_actualizar_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_actualizar_productos.setText("Gestionar Productos");
        jMenuItem_actualizar_productos.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_actualizar_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_actualizar_productosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_actualizar_productos);

        jMenuItem_gestionar_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_gestionar_productos.setText("Productos");
        jMenuItem_gestionar_productos.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_gestionar_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_productosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_gestionar_productos);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 0, 0));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pedidos_icon.png"))); // NOI18N
        jMenu4.setText("Pedidos");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItemMostrarPlatos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItemMostrarPlatos.setText("Mostrar menu");
        jMenuItemMostrarPlatos.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItemMostrarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarPlatosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemMostrarPlatos);

        jMenuRealizarPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuRealizarPedido.setText("Registrar Pedido");
        jMenuRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRealizarPedidoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuRealizarPedido);

        jMenuIPedidoComidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuIPedidoComidas.setText("Realizar Pedido Comidas");
        jMenuIPedidoComidas.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuIPedidoComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIPedidoComidasActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuIPedidoComidas);

        jMenuPedidoBebidas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuPedidoBebidas.setText("Realizar Pedido Bebidas");
        jMenuPedidoBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPedidoBebidasActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuPedidoBebidas);

        jMenuListaPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuListaPedido.setText("Lista Pedidos");
        jMenuListaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaPedidoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuListaPedido);

        jMenuBar1.add(jMenu4);

        jMenu6.setForeground(new java.awt.Color(0, 0, 0));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/promocion.png"))); // NOI18N
        jMenu6.setText("Promocion");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem13.setText("Nuevo Promocion");
        jMenuItem13.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuBar1.add(jMenu6);

        jMenu9.setForeground(new java.awt.Color(0, 0, 0));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu9.setText("Salir");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_salir.setText("Cerrar Sesion");
        jMenuItem_salir.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_salirActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem_salir);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIPedidoComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIPedidoComidasActionPerformed

        String tipoproducto = "Comida";
        FormInterPedidos formpedido = new FormInterPedidos();
        formpedido.TipoProduto(tipoproducto);
        jDesktopPane_menu.add(formpedido);
        formpedido.setVisible(true);
    }//GEN-LAST:event_jMenuIPedidoComidasActionPerformed

    private void jMenuItem_gestor_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestor_empleadosActionPerformed
        FormInterEmpleado interEmpleado = new FormInterEmpleado();
        jDesktopPane_menu.add(interEmpleado);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = interEmpleado.getSize();
        interEmpleado.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        interEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestor_empleadosActionPerformed

    private void jMenuItem_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_salirActionPerformed
        // Cierra la ventana principal
        this.dispose();

        // Abre la ventana de inicio de sesión
        FrmLogin formlogin = new FrmLogin();
        formlogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem_salirActionPerformed

    private void jMenuItem_gestionar_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_clientesActionPerformed
        FormInterCliente vistaClientes = new FormInterCliente();
        jDesktopPane_menu.add(vistaClientes);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = vistaClientes.getSize();
        vistaClientes.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        vistaClientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionar_clientesActionPerformed

    private void jMenuItem_gestionar_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_productosActionPerformed
        FormInterProducto vistaProductos = new FormInterProducto();
        jDesktopPane_menu.add(vistaProductos);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = vistaProductos.getSize();
        vistaProductos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        vistaProductos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_gestionar_productosActionPerformed

    private void jMenuItemMostrarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostrarPlatosActionPerformed
        FormInterMenus vistaComidas = new FormInterMenus();
        jDesktopPane_menu.add(vistaComidas);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = vistaComidas.getSize();
        vistaComidas.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        vistaComidas.setVisible(true);
    }//GEN-LAST:event_jMenuItemMostrarPlatosActionPerformed

    private void jMenuPedidoBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPedidoBebidasActionPerformed
        String tipoproducto = "Bebida";
        FormInterPedidos formpedido = new FormInterPedidos();
        formpedido.TipoProduto(tipoproducto);
        jDesktopPane_menu.add(formpedido);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = formpedido.getSize();
        formpedido.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formpedido.setVisible(true);

    }//GEN-LAST:event_jMenuPedidoBebidasActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FormInterPromociones formpromociones = new FormInterPromociones();
        jDesktopPane_menu.add(formpromociones);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = formpromociones.getSize();
        formpromociones.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formpromociones.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem_actualizar_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_actualizar_productosActionPerformed
        FormInterProduct formproduct = new FormInterProduct();
        jDesktopPane_menu.add(formproduct);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = formproduct.getSize();
        formproduct.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formproduct.setVisible(true);

    }//GEN-LAST:event_jMenuItem_actualizar_productosActionPerformed

    private void jMenuListaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaPedidoActionPerformed
        FormInterListPedidos pedidos = new FormInterListPedidos();
        jDesktopPane_menu.add(pedidos);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = pedidos.getSize();
        pedidos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        pedidos.setVisible(true);
    }//GEN-LAST:event_jMenuListaPedidoActionPerformed

    private void jMenuRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRealizarPedidoActionPerformed
        String tipoproducto = "Comida";
        FormInterPedidos formpedido = new FormInterPedidos();
        formpedido.TipoProduto(tipoproducto);
        jDesktopPane_menu.add(formpedido);
        Dimension desktopSize = jDesktopPane_menu.getSize();
        Dimension FrameSize = formpedido.getSize();
        formpedido.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        formpedido.setVisible(true);
        
    }//GEN-LAST:event_jMenuRealizarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIPedidoComidas;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItemMostrarPlatos;
    private javax.swing.JMenuItem jMenuItem_actualizar_productos;
    private javax.swing.JMenuItem jMenuItem_gestionar_clientes;
    private javax.swing.JMenuItem jMenuItem_gestionar_productos;
    private javax.swing.JMenuItem jMenuItem_gestor_empleados;
    private javax.swing.JMenuItem jMenuItem_salir;
    private javax.swing.JMenuItem jMenuListaPedido;
    private javax.swing.JMenuItem jMenuPedidoBebidas;
    private javax.swing.JMenuItem jMenuRealizarPedido;
    // End of variables declaration//GEN-END:variables
}
